# Generated by Django 3.0.8 on 2021-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hire_me',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(default='', max_length=50)),
                ('h_email', models.CharField(default='', max_length=50)),
                ('h_msg', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
